### ISSUE TITLE
Switch to TLN as default

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#45]
Tombs-Lester-Nachman implementation is faster than the original LN, and is scale invariant (see #44 ). Therefore it would be beneficial to switch to this method in the public-facing API.

We should retain the LN code if required for unit tests.

The Lally method should (for) probably be moved into a separate branch, so as not to include it in the next release, but to retain the ability to run experiments on it when desired.

**Comment by tpgillam** [comment]
@kesterlester : speaking to @Rupt , his version doesn't implement deci-sectioning. 

From your paper, this suggests that there would exist some cases that might be ~3x slower as a result (those that are near the kinematic minimum). Do you have a set of parameters for such an example so I can double check please & add it to the test suite? Thanks!

**Comment by tpgillam** [comment]
Rupert pointed out an example at the top of the `...v7.h` header file which seemed to have this property. I'll call this "example 2". Let's call "example 1" the one which is quoted on the README to this package.

I have run timings compare Lester (Deci-sectioning enabled), Lester (No DS), Tombs. In each case, we run the example 400 times, with the loop in C++ (thanks to numpy). This process is repeated 10000 times, so as to produce histograms for the evaluation time. Times are normalised by the batch size, so correspond to the "average time per computation within the batch".

Example 1:
![image](https://user-images.githubusercontent.com/7052222/115123411-d61bae00-9fb4-11eb-99ef-1b1b0bb57f07.png)

Far away from kinematic limit, DS makes no difference. There is a spread of evaluation times, as one might expect.

Example 2:
![image](https://user-images.githubusercontent.com/7052222/115123425-e59af700-9fb4-11eb-9d61-38c62b05032e.png)

Close to the limit... bizarre! DS seems to improve things somewhat, although this is dwarfed by some very strange variations! These were computed on my mac.

**Comment by Rupt** [comment]
Interesting and bizarre plots! :)

Just to check, does "example 1" use 400 mass pairings as listed under **Vectorisation**, or is it 400 repeats with identical arguments, as "example 2" must be?


> The Lally method should (for) probably be moved into a separate branch, so as not to include it in the next release, but to retain the ability to run experiments on it when desired.

Is this for licensing reasons?

**Comment by kesterlester** [comment]
My suspicion is that the funny things you are seeing are the result of an interplay between the sectioning process (whether it be bi or deci) which REDUCES search interval size, and, and the EXPANSION process that happens before sectioning in order to get both a lower and upper bound.  From memory, I think the expansion process could be a bit aggressive (e.g. increasing the top bound by a factor much larger than 2 at each step -- maybe even 5 or 10) so some of your events will use 2 such expansion stesp, some will use 3 expansions and some 4 ... and then (and only then) will the decisectioning/bisectioning kick in.  Each of the lumps will likely correspond to a different number of expansion steps.  My guess is that the number of expansion steps was broadly similar for the not-near-kinematic-bound examples you tried, but had about 3 main values for the near-kinematic-bound examples you tried.

**Comment by tpgillam** [comment]
@Rupt Example 1 & example 2 are both run in the same way. There are 400 repeats within C++; the same actual mass & momentum values are used for every evaluation. These repeats give a single timing point that goes into the histogram above.

> Is this for licensing reasons?

No; but we know that there exist cases where it doesn't give the right result, unfortunately. So it seems better (for now) not to include it to avoid confusion.

@kesterlester Possibly - but then I'm surprised because it appears to be non-deterministic. And also that Rupert's implementation (which should be equivalent to the no DS case) should see the same things.

**Comment by kesterlester** [comment]
I realise now that my last comment was posted under a misapprehension. I had thought that example 2 had (and example 1 had) some intrinsic variation within it. So that the inputs were not always identical. On re-reading this thread, I think I got the wrong end of the stick there. In that case, most of what I said in my last comment is irrelevant -- and I can't explain the timings.

**Comment by tpgillam** [comment]
I don't have a good explanation, however the "weirdness" seems related to numpy broadcastings. In any case, I'll be ignoring this now.

I quickly added "deciSectioning" to Rupert's implementation, and the penalty is a bit more than for yours (more like 10% slower in normal cases). Given that his impl is faster in the edge cases (but maybe not as fast as it could be), then for the sake of simplicity I think I'll go ahead with the migration without it.

I think adding it (or a version thereof) in could be a part of #36
